DATA_PREPROCESS_FOLDER_NAME : "data_preprocess"
POINTS_CLOUD:
  INPUT_FOLDER_NAME: "surface3d"
  OUTPUT_FOLDER_NAME: "surface3d"
  DOWNSAMPLE_CLASSES: [2,3] # Class of points that must be downsampled
  VOXEL_SIZE: [1.0,2.0] # Corresponding voxel size for the downsampling
  PIPEPLINE_PDAL_COLORIZATION_TEMPLATE_FILE_NAME: "PIPEPLINE_PDAL_COLORIZATION_TEMPLATE.json"
  PIPEPLINE_PDAL_REPROJECTION_TEMPLATE_FILE_NAME: "PIPEPLINE_PDAL_REPROJECTION_TEMPLATE.json"
ORTHOPHOTO:
  NO_DATA_VALUE: 0
  INPUT_FOLDER_NAME: "swissimage10"
  OUTPUT_FOLDER_NAME: "swissimage10"
  OUTPUT_FILE_NAME: "mergedTIF"
DIGITAL_SURFACE_MODEL:
  NO_DATA_VALUE: -9999
  INPUT_FOLDER_NAME: "surface3d-raster"
  OUTPUT_FOLDER_NAME: "surface3d-raster"
  OUTPUT_FILE_NAME: "mergedTIF"
